from pydantic import BaseModel
from typing import List, Optional, Dict, Any

class ChatRequest(BaseModel):
    query: str
    price_filter: Optional[str] = "Semua"
    top_n: Optional[int] = 5

class RecommendationItem(BaseModel):
    nama_rumah_makan: str
    alamat: str
    kategori: str
    range_harga: str
    kategori_harga: str
    menu: str
    deskripsi: str
    similarity_score: float
    maps_url: Optional[str] = None

class ChatResponse(BaseModel):
    query: str
    corrected_query: str
    warning_message: Optional[str] = None
    recommendations: List[RecommendationItem]

class RegistrationRequest(BaseModel):
    nama_rumah_makan: str
    alamat: str
    kategori: str
    range_harga: str
    menu: str
    suasana: Optional[str] = ""
    tipe_pengunjung: Optional[str] = ""
    fasilitas: Optional[str] = ""
    # Deskripsi, metadata, kategori_harga will be generated by system

class RegistrationResponse(BaseModel):
    status: str
    message: str

class StatsResponse(BaseModel):
    total_umkm: int
    categories: Dict[str, int]

class StatusCheckResponse(BaseModel):
    nama_rumah_makan: str
    status: str # 'pending', 'approved', 'not_found'
    message: str
